### ISSUE TITLE
Feature request: Google Hangouts integration

### ISSUE THREAD

**Issue by Feichtmeier** [nylas/nylas-mail#1535] opened 2016-03-01 22:38 UTC
I would love to see the Google Calendar integrated into Nylas. I know it is somehow in there via the quick schedule plugin but a full integration would be really nice. Hangouts would be an extra :)

**Comment by physicalit** [comment] 2016-03-02 09:26
I wold rather see it as a plugin, actually to separated plugins.

**Comment by mbilker** [comment] 2016-03-03 22:44
Dupe of #298

**Comment by Feichtmeier** [comment] 2016-03-04 06:55
Maybe integrate the chat windows into nylas and use the libnotifysend which seems to be allready integrated into nylas (Linux) to receive notifications. The calls could be linked into a browser window just how it is in the chrome app?
The chat windows could be integrated like the old hangouts "hovering bubbles" design which they disabled by default some time ago.

![image](https://cloud.githubusercontent.com/assets/15329494/13520183/6a6e2960-e1de-11e5-969d-e212087b9bfa.png)

**Comment by jackiehluo** [comment] 2016-07-12 07:02
Another request: https://nylas.zendesk.com/agent/tickets/4643

**Closed** 2020-10-28 11:51 UTC
Labels: enhancement-request
