### ISSUE TITLE
Stuck on "Looking for Messages" v1.0.21

### ISSUE THREAD

**Issue by amicablewings** [nylas/nylas-mail#3268] opened 2017-02-06 17:49 UTC
It wont load the initial set of google emails. It stays stuck on Looking for Messages. Resetting the catch does not fix the issue either. 

It does load the folders but wont download the messages. 

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of Nylas Mail are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by adnanoner** [comment] 2017-02-07 09:13
Perhaps you have a third-party plugin installed. I have the unsubscribe plugin installed, and updated it, and the problem was fixed.

**Comment by TheRealGitCub** [comment] 2017-02-07 16:48
Duplicate of #3232

**Closed** 2017-02-07 22:34 UTC

**Comment by jstejada** [comment] 2017-02-07 23:02
merging into duplicat
