### ISSUE TITLE
Feature Request: Manual mapping of folders for Sent Mail, Trash etc.

### ISSUE THREAD

**Issue by wadedog** [nylas/nylas-mail#1457] opened 2016-02-26 23:24 UTC
I have a bunch of map accounts that I want to use in Nylas N1. But when I add them it doesn't map the "Deleted Messages" mailboxes to Trash.

What this means is that I cannot delete anything as Nylas thinks there is nowhere for it to go.

In mail.app you can click on any mailbox and get then select Mailbox > Use This Mailbox As > and then select something like Trash Mailbox and abracadabra it's now mapped and any deletes sends the email to that mailbox.

At the moment (0.4.9.575c091) I cannot find where/if this can be done, and without it all the imap accounts are useless because I can't even delete an email.

**Comment by bengotow** [comment] 2016-02-26 23:27
Hi @wadedog — thanks for filing this. Can you post one of the email addresses that isn't being mapped properly? If it's sensitive, feel free to also email us at support@nylas.com. We could add an option for doing this, but we'd much rather make it work as expected in the first place! Cheers—

**Comment by wadedog** [comment] 2016-02-26 23:34
Hi @bengotow, 

Sorry for my ignorance but how will sending you an email address help...?

This affects all of my IMAP accounts that are not Google. They are hosted on my own server.

With IMAP people can set any mailbox they want as trash, sent, archive etc. So every system can differ depending on the host etc.

Mine are called Sent Messages and Deleted Messages.

What names of mailboxes is Nylas looking for...?

**Comment by MoOx** [comment] 2016-02-28 07:27
Having the same issue. Mail deleted in Mail.app seems to be moved to my account Trash, but in reallity, they are not moved anywhere (even if I got a Trash label in Mail.app).
If I use my webmail provider (roundcube) I can see that mail supposed to be deleted are still in inbox but just in a very light color compared to the other (see attachements).
You will also not the "start" column with a symbol that may mean "deleted".

![screen shot 2016-02-28 at 08 21 14](https://cloud.githubusercontent.com/assets/157534/13378009/cb91aca0-ddf4-11e5-905c-e0729ac281cd.png)

Not sure what is the best to do. Mail.app say from its configuration that messages should be in a Trash folder.

![screen shot 2016-02-28 at 08 26 00](https://cloud.githubusercontent.com/assets/157534/13378012/f0228ce2-ddf4-11e5-98ae-d6fc12a3ea7b.png)

FYI, It's a simple IMAP account at gandi.net

**Comment by jamesbeston** [comment] 2016-03-09 08:31
Same issue here across accounts but mainly my Gmail. I don't see an option to change mapping / labelling and, with 50% of emails remaining in my Inbox with a 'Bin' label, it is preventing me using it.

Has this been resolved yet?

**Comment by MoOx** [comment] 2016-03-09 08:32
If  the issue is still open, probably not resolved yet.
It's also preventing me trying n1 :(

**Comment by thosgood** [comment] 2016-03-24 16:57
This is an issue for me also. I'm using a university email address (accessible through IMAP) and the trash folder is called 'Deleted Items'. It shows up in the list of folders for that account, but not in the 'Bin' section of folders. This is annoying mostly because it means I can't delete emails, except by dragging them to the Deleted Items folder each time.

**Comment by FlorianBrinkmann** [comment] 2016-04-12 07:46
I have the same problem!

**Comment by jamesbeston** [comment] 2016-04-12 10:42
I have noticed that since the latest update that this issue has disappeared! I
have now got rid of Thunderbird and so far, so good!

> On Apr 12 2016, at 9:34 am, Florian Brinkmann
&lt;notifications@github.com&gt; wrote:  

>

> I have the same problem!

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1457#issuecomment-208761433)![](https://github.com/notifications/beac
on/AAwmrQObGoYgmyE5eXCwjtlJ44mRL7Qvks5p203wgaJpZM4HkRMz.gif)

**Comment by MoOx** [comment] 2016-04-12 21:49
FYI, I successfully converted my imap account to work with latest n1.

http://apple.stackexchange.com/questions/19251/how-can-i-re-map-mails-sent-messages-folder-to-an-imap-servers-sent-mail-f

For example renamed "Deleted messages" to "Sent" and ask Mail.app to use it via "Mailbox" in menubar, then "Use mailbox as" as explained in the previous link. Also did the same for Trash, and then I got the same result in Mail.app and n1.

**Comment by FlorianBrinkmann** [comment] 2016-04-13 06:41
Problem soved, I had to rename the folders in Roundcube from the german name to english (for example ”Gesendet“ to ”Sent“).

**Comment by thosgood** [comment] 2016-04-15 20:50
None of the above suggestions have solved the problem for me -- neither the 'Sent Items' nor the 'Deleted Items' folder show on the list of all folders in the left sidebar, but they also don't appear under the 'Sent' or 'Bin' dropdowns (unlike my gmail).

**Comment by tomkeysers** [comment] 2016-04-20 10:56
I'm having issues with this as well. 
Just testing this mail client and added an IMAP account. I now see folders like 'INBOX.Archive' and 'INBOX.INBOX.Trash' in N1, but none of these folders work with the shortcuts.

It's really important for me to be able to archive and delete mails with a shortcut. 

Should I get this working if I rename these folders? Have tried 'Archive' and 'Trash', but not working ...

**Comment by xRokco** [comment] 2016-04-22 08:21
I'm having this issue too. If I create a folder folderName in Thunderbird, it will appear in N1 as INBOX/folderName. If I rename the folder in N1 (for example changing INBOX/Trash to Trash) the background icon of the empty folder will turn into a Trash bin, so N1 is understanding the name, but I still have no option to delete/trash emails anywhere.

I'm using an IMAP account.

**Comment by Legoblokje** [comment] 2016-04-29 08:42
I have the same issue. For example Inbox is marked as INBOX and works, but Sent / Trash are marked as INBOX.Sent / INBOX.trash and don't work. I think a manual mapping function would solve these issues.

**Comment by Legoblokje** [comment] 2016-05-03 07:32
The new stable version (version 0.4.32-1de17e7) fixed my problems. The names of the folders are still INBOX.Foo, but they are functional.

**Comment by xRokco** [comment] 2016-05-03 09:17
New update didn't fix it for me. I reset my mailbox with my mailserver provider and still no luck. Default folder setup below.

![inbox](https://cloud.githubusercontent.com/assets/4988873/14979117/3fea0e02-1118-11e6-8530-7db92df26787.png)

**Comment by tomkeysers** [comment] 2016-05-04 08:14
The update worked half for me. N1 now successfully recognizes the Archive and Trash folder, but NOT the Sent folder. So sent messages from N1 aren't saved anywhere ...

**Comment by andremrsantos** [comment] 2016-05-06 15:37
It would be nice to able to map a folder as trash and sent in this case. I have the same issues, but my university email doesn't allow me to rename INBOX/Trash to anything else

**Comment by rgruyters** [comment] 2016-05-23 07:33
It would be a nice add-on if users can select/map folders. For me I use a different Trash folder than the default "Trash". (I use "Deleted Messages")

**Comment by iraklisg** [comment] 2016-07-06 06:14
@xRokco I use Nylas to connect to my outlook.com account. I have a similar problem, some time ago I manually created an Archive folder, which I deleted later on. However, the folder still appears in my folders panel as, Deleted items\Archive. I tried numerous ways to make it disappear including deleting this string ```
"serializedCategories":"[{\"client_id\":\"local-9ff7eb04-aa84\",\"server_id\":\"2tpd67o9t5o5o9o0j1cer8mpm\",\"object\":\"folder\",\"account_id\":\"3yd92emoljq3px8fhpoam2ayc\",\"name\":\"archive\",\"display_name\":\"Deleted Items\\\\Archive\",\"id\":\"2tpd67o9t5o5o9o0j1cer8mpm\",\"__constructorName\":\"Category\"}]"
   },
``` from the ~/.nylas/main-window-state.json but it stills there (btw the folder does not appear in my webmail)

**Comment by jackiehluo** [comment] 2016-07-06 19:21
Another incidence: https://nylas.zendesk.com/agent/tickets/3672

**Comment by jackiehluo** [comment] 2016-07-08 17:44
Another incidence: https://nylas.zendesk.com/agent/tickets/4370

**Comment by jackiehluo** [comment] 2016-07-13 18:14
Another incidence: https://nylas.zendesk.com/agent/tickets/4157

**Comment by jackiehluo** [comment] 2016-07-13 18:35
Another incidence: https://nylas.zendesk.com/agent/tickets/92

**Comment by jackiehluo** [comment] 2016-07-15 17:52
Another incidence: https://nylas.zendesk.com/agent/tickets/4998

**Comment by hallamoore** [comment] 2016-07-26 21:58
Hi everyone,

We have deployed a partial patch for this. Now our code tries to infer which folders are trash/sent/etc if we don't receive specific flags from your IMAP provider. So, folders with names like Deleted Messages or INBOX/trash should get correctly parsed as the trash folder. However, if you have multiple folders that could be interpreted as one of these default folders, we don't choose any of them, since we don't actually know which one would be correct.

We will eventually add an interface for manually setting the default folders, but for now this should solve the issue for most of you. Are any of you still experiencing this problem?

Thanks!
Halla

**Comment by spenserhale** [comment] 2016-07-27 20:47
@hallamoore 

I am running Version 0.4.45-7637265 and checked for updates but says on latest version.

I do not see the any change with deleted folders for my IMAP account.

Is there a step I need to do to run the code inference?

**Comment by hallamoore** [comment] 2016-07-28 19:23
Hi @spenserhale — No, you shouldn't need to do anything else. What behavior is your account still exhibiting?

**Comment by happydemic** [comment] 2016-07-31 14:13
Nylas 04.47-3a2a94c
IMAP via locally hosted sync engine
Deleted Items folder not detected

- my IMAP provider automatically creates a deleted mail folder called "Deleted Items"
- With ***no*** similarly named folders, i.e. no "Trash", "Deleted Mail", "Bin" etc., Nylas does not detect the Deleted Items folder and I cannot delete mail.
- If I create a Trash folder (in addition to the Deleted Items folder created automatically by my account), Nylas detects it and sets it as the Trash, meaning I can delete messages into it.
- @hallamoore, If I create a folder called "Deleted Messages", Nylas does not detect it. Perhaps I am running the wrong commit.

**Comment by hallamoore** [comment] 2016-08-03 18:08
@happydemic, hmm, let's make sure you do have the right commit with your local sync engine. The relevant sync-engine commit is [f57372](https://github.com/nylas/sync-engine/commit/f5737284418ac4c94650b9d6e7c8e1a2cfc81c50).

**Comment by happydemic** [comment] 2016-08-03 21:04
Hi there, thanks for commenting. 

I'm currently running sync-engine [91744eb](https://github.com/nylas/sync-engine/commit/91744eb3fbe8f1deb70066af481cc12b2f3b8b6e) (2 Aug) which includes [f57372](https://github.com/nylas/sync-engine/commit/f5737284418ac4c94650b9d6e7c8e1a2cfc81c50) (28 June). I even checked my sync engine's inbox/folder_edge_cases.py file to see that it has the correct code, which it does (below): 
![screenshot from 2016-08-03 21-57-35](https://cloud.githubusercontent.com/assets/12738878/17381749/6d60cc2c-59c5-11e6-8b21-8d755586ae54.png)

N1 can't still identify "Deleted Items" as the trash folder. Perhaps this is because the sync engine database was created before that commit. I don't want to regenerate the database because that takes many hours of high CPU use in my setup.

**Comment by hallamoore** [comment] 2016-08-03 21:21
I believe folder roles are assigned with each sync, so you shouldn't have to regenerate the database. Can you double check that when you hit your sync engine's "/folders" endpoint none of the folders have `"name": "trash"`?

**Comment by happydemic** [comment] 2016-08-03 22:09
Checked - and nope.  The list is too long for a screenshot, but Deleted Items appears as ``` "name": null ``` and there are no folders with ```"name": "trash"```.

**Comment by hallamoore** [comment] 2016-08-05 17:32
@happydemic 

Could you do some debugging around [https://github.com/nylas/sync-engine/blob/master/inbox/crispin.py#L533](https://github.com/nylas/sync-engine/blob/master/inbox/crispin.py#L533)? Double-check that _guess_role() is being called for your "Deleted Items" folder, and that `localized_folder_names[role]` for when the role is 'trash' is the expected list from [https://github.com/nylas/sync-engine/blob/master/inbox/folder_edge_cases.py](https://github.com/nylas/sync-engine/blob/master/inbox/folder_edge_cases.py). Thanks!

**Comment by happydemic** [comment] 2016-08-07 18:38
@hallamoore

Running sync-engine [0722050](https://github.com/nylas/sync-engine/commit/072205068158be05d3d513fcd480534a9734011f) (6 Aug). 

Thanks again for looking into this. I checked out your suggestion, but no luck unfortunately. :(

To answer your questions specifically regarding [_guess_role()](https://github.com/nylas/sync-engine/blob/master/inbox/crispin.py#L533):  _guess_role() is called for "Deleted Items", ```localized_folder_names``` has the expected values, and ```role``` is returned correctly as 'trash' - see [gist](https://gist.github.com/happydemic/50ec4840d578a22da5f4514b6b9f9648). 

I then stepped through and confirmed that the value of ```missing_roles``` (i.e. after matching against the defaults only) is  ['trash', 'spam'], as expected, and the correct (guessed) folder mapping for 'Deleted Items' is included by crispin.py in ```raw_folders``` and then passed to monitor.py as ```remote_folders```. So my value for ```remote_folders[3]``` at line 50 of monitor.py is  RawFolder(display_name=u'Deleted Items', role='trash') - I believe that is all as expected.

What next?

As a separate issue, I noticed that folder_edge_cases is currently missing the British English mappings for 'spam', viz 'Junk Mail', 'Junk E-Mail' etc. The spam folder on that particular account is 'Junk E-Mail'.

**Comment by hallamoore** [comment] 2016-08-12 21:20
Hi @happydemic,

I just merged some sync-engine code that should hopefully solve this problem. I don't know when it'll make it to production, but since you're running a self-hosted sync engine, feel free to pull it and test it out! The relevant commit is [92313a](https://github.com/nylas/sync-engine/commit/92313a289abe74cdf8f1e014df8d17620d146cad).

**Comment by wadedog** [comment] 2016-08-13 00:29
A fuzzy matching solution that doesn't pick up everything is still unusable for a lot of people. 

I simply can't use N1 until I can map folders like I can in mail.app. If N1 doesn't find the folders it thinks should be there you can't delete emails.

17 days ago you said it was a partial patch and "We will eventually add an interface for manually setting the default folders". 

This feature shouldn't be closed because it hasn't been delivered.

**Comment by happydemic** [comment] 2016-08-13 06:48
Hi @hallamoore , I agree with @wadedog - there are two separate issues here. 

1. The absence of manual mapping is a big limitation. This issue should be relabelled as **enhancement-request** (not bug). The issue should either be reopened or closed as wontfix (if that's the decision), but it should be on Nylas's radar.

2. Regarding the patch for the bug in fuzzy matching, it looks promising, but when I updated to that commit, the account went to sync_state:invalid. Hopefully that is a coincidence, but it still means I can't test the patch. I'll update once I've got the account sync back up.

**Comment by happydemic** [comment] 2016-08-13 15:08
@hallamoore, this patch does not seem to solve the fuzzy matching bug entirely I'm afraid.

I have moved the discussion of the fuzzy matching to nylas/sync-engine#377.

**Comment by hallamoore** [comment] 2016-08-13 18:11
Whoops, GitHub automatically closed the issue because I referenced it in a pull request. I'll reopen this for the mapping feature request, and I think the sync engine issue is a good place to continue the fuzzy matching discussion. Thanks!

**Comment by jackiehluo** [comment] 2016-08-22 17:19
Another incidence: https://nylas.zendesk.com/agent/tickets/5733

**Comment by WESID** [comment] 2016-08-27 18:08
I have just downloaded Nylas and added three accounts. Two of them have everything but one of them, an IMAP account, has nothing in the sent folder. The other two accounts do. What do I need to do?

**Comment by WESID** [comment] 2016-08-27 18:12
I have just downloaded Nylas and added three accounts. Two of them have everything but one of them, an IMAP account, has nothing in sent folder. The other two accounts do. What do I need to do?

**Comment by spenserhale** [comment] 2016-12-28 16:08
Any updates? I am still unable to use Nylas due to unable to delete emails.

**Comment by firefountain** [comment] 2017-02-15 11:17
Same here.. IMAP account can't find the "Sent" folder..

**Comment by ArchangeGabriel** [comment] 2017-02-16 11:41
Manual mapping is a necessary feature for me, and it would be much less code than trying to cope with every possibility, especially localized ones. I have several accounts for which I can’t change the folder name on the server side, and from this issue I bet that Nylas Mail wouldn’t recognize them (I’ll be able to confirm that eventually once Nylas Mail will be build-able from source and won’t depend anymore on a remote part, which are both necessary condition for me to try Nylas software).

**Comment by tchiotludo** [comment] 2017-04-13 11:16
I find a solution to have a partial working version.
Nylas seems to seek folder (like the gmail for Android) at the root.

So you need to have at root : 
* INBOX 
* Trash 
* Sent
* Junk
* Drafts 

This version works well for the Trash : 
![image](https://cloud.githubusercontent.com/assets/2064609/25001398/ae919252-2045-11e7-9b6d-7543dc7ae165.png)

No more Trash folder at the bottom, but don't work for others.

When I send a mail, this popup appear : 
![image](https://cloud.githubusercontent.com/assets/2064609/25001442/d52e1444-2045-11e7-8d42-ab02f9d08a34.png)

Clicking "Show Details" only close the popup, log output : 
```
{"host":"udol","timestamp":"2017-04-13T10:38:22.582Z","payload":"Error: Can't find sent folder - could not save message to sent folder.
    at NylasError (errors.es6:1:8)
    at APIError (errors.es6:17:5)
    at /internal_packages/client-sync/src/local-sync-worker/syncback-tasks/ensure-message-in-sent-folder.imap.es6:43:30
    at next (<anonymous>)
    at resume (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/ensure-message-in-sent-folder.imap.js:3:448)
    at /usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/ensure-message-in-sent-folder.imap.js:3:367
    at AsyncGenerator.send [as _invoke] (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/ensure-message-in-sent-folder.imap.js:3:169)
    at advance (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:78:31)
    at err (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:110:17)"}
{"host":"udol","timestamp":"2017-04-13T10:38:22.584Z","payload":{"fingerprint":["{{ default }}","syncback task","Can't find sent folder - could not save message to sent folder."],"pluginIds":["client-sync"]}}
{"host":"udol","timestamp":"2017-04-13T10:38:22.588Z","payload":"{ Error: Can't find sent folder - could not save message to sent folder.
    at NylasError (errors.es6:1:8)
    at APIError (errors.es6:17:5)
    at /internal_packages/client-sync/src/local-sync-worker/syncback-tasks/ensure-message-in-sent-folder.imap.es6:43:30
    at next (<anonymous>)
    at resume (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/ensure-message-in-sent-folder.imap.js:3:448)
    at /usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/ensure-message-in-sent-folder.imap.js:3:367
    at AsyncGenerator.send [as _invoke] (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/ensure-message-in-sent-folder.imap.js:3:169)
    at advance (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:78:31)
    at err (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:110:17)
  message: 'Can\\'t find sent folder - could not save message to sent folder.',
  __stackCleaned__: true } { fingerprint: 
   [ '{{ default }}',
     'syncback task',
     'Can\\'t find sent folder - could not save message to sent folder.' ],
  pluginIds: [ 'client-sync' ] }
"}

```

So ugly hack that work well, go to :  
* ~/.nylas-mail/random.sqlite
* open dabase with a [gui](https://apps.ubuntu.com/cat/applications/natty/sqlitebrowser/) when nylas is closed
* open tables folders and add role to your folder (inbox, trash, sent, drafts, spam)
* save database 
* restart nylas
* enjoy

**Comment by nairbinod** [comment] 2017-04-18 14:42
~/.nylas-mail/random.sqlite
open dabase with a gui when nylas is closed
open tables folders and add role to your folder (inbox, trash, sent, drafts, spam)
save database
restart nylas

THIS WORKED

**Comment by hallamoore** [comment] 2017-04-18 18:18
We're also going to release an in-app gui for this soon!

**Comment by jstejada** [comment] 2017-04-25 18:33
this will be released in the next release!

**Comment by jstejada** [comment] 2017-04-27 17:44
this has been released today!

**Closed by jstejada** 2017-04-27 17:44 UTC
Labels: done-pending-release, enhancement-request, mail-sync

**Comment by WESID** [comment] 2017-04-27 17:49
Please delete me from this list.

**Comment by WESID** [comment] 2017-04-27 17:49
Please delete me from this list!

**Comment by MidnightLightning** [comment] 2017-04-27 18:08
@WESID You're receiving those emails because you're subscribed to an Issue thread in GitHub. In the emails you're receiving, look at the bottom of the email, and you'll see a "mute this thread" option. Click that and you won't receive further notifications on that thread.

**Comment by MidnightLightning** [comment] 2017-04-27 18:34
@jstejada The mapping of folders does not allow setting an "Archive" folder, for IMAP accounts to be able to use the "archive" action.

**Comment by WESID** [comment] 2017-04-27 18:46
Please take me off the list. I do not remember my password for the list 
so I can't even get out to "mute" it.

**Comment by basma-b** [comment] 2017-05-17 12:41
@tchiotludo please i can't find the db in the path u mentioned

**Comment by tchiotludo** [comment] 2017-05-17 12:43
@basma-b : i'm on linux, don't know the path on windows.
And if you update your nylas, there is a Gui now that works well
