### ISSUE TITLE
Error while saving e-mail after send

### ISSUE THREAD

**Issue by Laul** [nylas/nylas-mail#3222] opened 2017-01-26 04:47 UTC
##### Are there any related issues?

Not found any similar issue

##### What operating system are you using?
Mac - Sierra OS 10.12.2

##### What version of N1 are you using?
v1.0.11

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have Gmail accounts so I don't know

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I got the following message 2 or 3 times from the time I use Nylas (i.e. less than 2 weeks) but I did not found reproducible steps to generate similar errors:
```
Your message successfully sent; however, we had trouble saving your message, "", to your Sent folder.
Cannot make Nylas request without specifying `auth` or an `accountId`.

```
<img width="408" alt="error-sentmessage" src="https://cloud.githubusercontent.com/assets/2975027/22320232/6161f69a-e358-11e6-8e5c-f3e5b730eb2a.png">

Clicking on "Show Details" give this information:
```
Error
    at new APIError (/src/flux/errors.es6:28:19)
    at NylasAPIRequest.run (/src/flux/nylas-api-request.es6:111:31)
    at /src/flux/syncback-task-api-request.es6:72:53
    at next (<anonymous>)
    at step (/src/flux/syncback-task-api-request.es6:5:1)
    at Promise._execute (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:77:14)
    at /src/flux/syncback-task-api-request.es6:5:1
    at Promise._execute (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:77:14)
    at SyncbackTaskAPIRequest.run (/src/flux/syncback-task-api-request.es6:70:12)
    at EnsureMessageInSentFolderTask.performRemote (/src/flux/tasks/ensure-message-in-sent-folder-task.es6:50:10)
    at EnsureMessageInSentFolderTask.runRemote (/src/flux/tasks/task.es6:230:19)
    at TaskQueue._processTask (/src/flux/stores/task-queue.coffee:237:10)
    at TaskQueue._processTask (/src/flux/stores/task-queue.coffee:1:1)
    at TaskQueue._processQueue (/src/flux/stores/task-queue.coffee:224:8)
    at TaskQueue._processQueue (/src/flux/stores/task-queue.coffee:1:1)
    at /src/flux/stores/task-queue.coffee:351:10
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/underscore/underscore.js:768:19
```

Thank you for your help, 
Lauranne

**Comment by jstejada** [comment] 2017-01-28 00:59
thanks for the report! e're going to look into it

**Comment by monkeydri** [comment] 2017-02-13 10:52
I have a similar error but the error message is slightly different :

![nylas-send-bug-msg](https://cloud.githubusercontent.com/assets/18724661/22880347/1bb60080-f1e2-11e6-84a9-d2764bd3b873.png)


```
Error

Your message successfully sent; however, we had trouble saving your message, "test send from tmc", to your Sent folder.

Syncback Task Failed: Can't find sent folder - could not save message to sent folder.
```





when clicking show details :

```
Error
    at new APIError (/src/flux/errors.es6:29:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:29:25)
    at EventEmitter.eventHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/internal_packages/deltas/lib/delta-processor.es6:140:13)
    at /internal_packages/deltas/lib/delta-processor.es6:78:12
    at next (<anonymous>)
    at step (/internal_packages/deltas/lib/delta-processor.es6:2:1)
    at /internal_packages/deltas/lib/delta-processor.es6:2:1
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```


- operating system : Mac - Sierra OS 10.12.3
- Nylas Mail version :  v1.0.21. did not have the problem with Nylas N1  and custom sync-engine.
- third-party plugins installed : none
- issue related to a specific email provider : happens only on my OVH mail account (IMAP). I have another IMAP account with a different provider but email cannot even be sent so I can't tell if problem does happen on this account too...
- issue reproducibility : happens every time I send a mail, regarding subject, recipient or wether there is a signature or not.

**Comment by monkeydri** [comment] 2017-02-14 09:10
same error after update to Nylas Mail 1.0.26

**Comment by sethwebster** [comment] 2017-02-14 16:24
+1

**Comment by jstejada** [comment] 2017-02-15 02:37
a fix for this will be released soon!

**Comment by monkeydri** [comment] 2017-02-23 21:52
Well, problem is still there with 1.0.29 ...

**Comment by jstejada** [comment] 2017-02-24 05:44
hi @monkeydri ! I believe you are seeing an instance of #3212?

**Closed by jstejada** 2017-02-24 05:44 UTC
Labels: done-pending-release

**Comment by monkeydri** [comment] 2017-02-24 06:34
@jstejada Yes you're right I think, the problem is the Sent folder of the culprit IMAP account is not mapped correctly (it does not appear in the Unified Sent folder).
